package pl.codziennik.app

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.graphics.Color
import android.graphics.Paint
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.view.View
import android.widget.*
import pl.codziennik.app.data.Habit
import java.text.SimpleDateFormat
import java.util.Locale

class CodziennikScreens(private val activity: MainActivity) {
    private val cream=Color.rgb(242,235,221); private val forest=Color.rgb(35,58,42); private val sage=Color.rgb(104,116,90); private val gold=Color.rgb(184,137,85)
    private val backgrounds=listOf(R.drawable.bg_lake,R.drawable.bg_forest,R.drawable.bg_mountains,R.drawable.bg_grass,R.drawable.bg_meadow)
    private val prefs=activity.getSharedPreferences("codziennik",0)
    private val day get()=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(activity.selectedDate.time)
    private val label get()=SimpleDateFormat("EEEE, d MMMM",Locale("pl","PL")).format(activity.selectedDate.time).replaceFirstChar { it.uppercase() }
    private fun dp(v:Int)=(v*activity.resources.displayMetrics.density).toInt()
    private fun shape(color:Int,r:Int=20)=GradientDrawable().apply { setColor(color);cornerRadius=dp(r).toFloat() }
    private fun text(v:String,size:Float=16f,color:Int=forest)=TextView(activity).apply { text=v;textSize=size;setTextColor(color) }
    private fun action(v:String, f:()->Unit)=TextView(activity).apply { text=v;gravity=Gravity.CENTER;setPadding(dp(8),dp(8),dp(8),dp(8));setTextColor(forest);setOnClickListener{f()} }
    private fun base(title:String, subtitle:String=label): LinearLayout { val root=FrameLayout(activity); root.setBackgroundColor(cream); val body=LinearLayout(activity).apply { orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(28),dp(18),dp(88)) }; root.addView(ScrollView(activity).apply { addView(body) }); root.addView(bottom(),FrameLayout.LayoutParams(-1,dp(70),Gravity.BOTTOM)); activity.setContentView(root); body.addView(LinearLayout(activity).apply { gravity=Gravity.CENTER_VERTICAL;addView(action("‹") { showHome() },LinearLayout.LayoutParams(dp(42),dp(42)));addView(LinearLayout(activity).apply { orientation=LinearLayout.VERTICAL;addView(text(title,27f));addView(text(subtitle,12f,sage)) },LinearLayout.LayoutParams(0,-2,1f));addView(action("⌕") { Toast.makeText(activity,"Wyszukiwanie będzie dostępne po zapisaniu większej historii.",Toast.LENGTH_SHORT).show() },LinearLayout.LayoutParams(dp(42),dp(42))) }); return body }
    private fun bottom()=LinearLayout(activity).apply { setBackgroundColor(forest);gravity=Gravity.CENTER; val items=listOf("Start" to "home","Zadania" to "tasks","+" to "tasks","Kalendarz" to "calendar","Więcej" to "more");items.forEachIndexed { i,(name,route)->addView(action(name){activity.open(route)}.apply { setTextColor(if(i==2) gold else cream);textSize=if(i==2)28f else 12f },LinearLayout.LayoutParams(0,-1,1f)) } }
    private fun card(title:String, hint:String, dark:Boolean=false, click:()->Unit)=LinearLayout(activity).apply { orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(14));background=shape(if(dark) forest else Color.WHITE);setOnClickListener{click()};addView(text(title,18f,if(dark) cream else forest));addView(text(hint,12f,if(dark) Color.rgb(217,198,165) else sage).apply{setPadding(0,dp(4),0,0)}) }

    fun showHome() { val body=base("Codziennik","Małe kroki, wielkie zmiany · $label"); body.addView(text("Spokojna przestrzeń na dzisiejsze małe kroki.",15f,sage).apply { setPadding(0,dp(18),0,dp(12)) }); val tiles=GridLayout(activity).apply { columnCount=2 }; val entries=listOf("Moje zadania" to "tasks","Lista zakupów" to "shopping","Kalendarz" to "calendar","Statystyki" to "stats","Zdjęcie dnia" to "photos","Ogród" to "garden","Kuchnia" to "kitchen","Podróże" to "travel","Ustawienia" to "settings");entries.forEachIndexed { index,(name,route)->tiles.addView(card(name, if(name=="Moje zadania") progress() else "Otwórz",index%3==1){activity.open(route)},GridLayout.LayoutParams().apply { width=0;height=dp(104);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);setMargins(dp(4),dp(4),dp(4),dp(4)) }) };body.addView(tiles);body.addView(card("Pamiątka z dnia","Jedno prywatne zdjęcie, jeśli chcesz."){activity.open("photos")},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(12)});body.addView(card("Notatki","Zapisz to, co warto zachować."){noteDialog()},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});body.addView(card("Nastrój","Moduł nastroju przygotujemy w kolejnym etapie."){Toast.makeText(activity,"Nastrój nie jest jeszcze zapisywany.",Toast.LENGTH_SHORT).show()},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)}) }
    private fun progress():String { val h=activity.database.habits();return "${activity.database.completed(day).count{ id->h.any{it.id==id} }}/${h.size} wykonanych" }
    fun showTasks() { val body=base("Moje zadania");body.addView(action("＋ Dodaj na dziś") { editHabit(null) }.apply { background=shape(Color.rgb(217,198,165));setPadding(0,dp(12),0,dp(12)) }); val habits=activity.database.habits();if(habits.isEmpty()) body.addView(text("Brak zadań na ten dzień.",15f,sage));habits.forEach { habit->taskCard(body,habit) } }
    private fun taskCard(body:LinearLayout,habit:Habit) { val done=activity.database.completed(day).contains(habit.id);val subs=activity.database.subtasks(day,habit.id);val row=LinearLayout(activity).apply { orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(10),dp(10),dp(10));background=shape(Color.WHITE);val top=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL};val check=CheckBox(activity).apply{text=habit.title;textSize=17f;isChecked=done;setTextColor(forest);if(done)paintFlags=paintFlags or Paint.STRIKE_THRU_TEXT_FLAG;setOnCheckedChangeListener{_,v->activity.database.setCompleted(day,habit.id,v);showTasks()}};top.addView(check,LinearLayout.LayoutParams(0,-2,1f));top.addView(action("⋮"){taskMenu(habit)});addView(top);if(subs.isNotEmpty())addView(text("Podzadania: ${subs.count{it.completed}}/${subs.size}",12f,sage));subs.forEach{s->addView(CheckBox(activity).apply{text=s.title;isChecked=s.completed;setTextColor(sage);if(s.completed)paintFlags=paintFlags or Paint.STRIKE_THRU_TEXT_FLAG;setOnCheckedChangeListener{_,v->activity.database.setSubtask(s.id,v);showTasks()})} };body.addView(row,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)}) }
    private fun taskMenu(h:Habit){AlertDialog.Builder(activity).setItems(arrayOf("Dodaj podzadanie","Edytuj","Usuń")){_,w->when(w){0->subtaskDialog(h);1->editHabit(h);2->{activity.database.deleteHabit(h.id);showTasks()}}}.show()}
    private fun subtaskDialog(h:Habit){val input=EditText(activity).apply{hint="Nazwa podzadania"};AlertDialog.Builder(activity).setTitle("Dodaj podzadanie").setView(input).setPositiveButton("Dodaj"){_,_->if(!activity.database.addSubtask(day,h.id,input.text.toString()))Toast.makeText(activity,"Maksymalnie 5 podzadań.",Toast.LENGTH_SHORT).show();showTasks()}.setNegativeButton("Anuluj",null).show()}
    private fun editHabit(h:Habit?){val input=EditText(activity).apply{hint="Nazwa zadania";setText(h?.title ?: "")};AlertDialog.Builder(activity).setTitle(if(h==null)"Nowe zadanie" else "Edytuj zadanie").setView(input).setPositiveButton("Zapisz"){_,_->if(input.text.trim().isNotEmpty()){if(h==null)activity.database.addHabit(input.text.toString()) else activity.database.renameHabit(h.id,input.text.toString());showTasks()}}.setNegativeButton("Anuluj",null).show()}
    fun showShopping(){val body=base("Lista zakupów");body.addView(action("＋ Dodaj produkt"){shoppingDialog()}.apply{background=shape(Color.rgb(217,198,165))});val items=activity.database.shopping();if(items.isEmpty())body.addView(text("Lista jest pusta.",15f,sage).apply{setPadding(0,dp(18),0,0)});items.forEach{i->body.addView(CheckBox(activity).apply{text=i.title;isChecked=i.checked;setTextColor(forest);contentDescription="${i.title}. Przytrzymaj, aby usunąć.";if(i.checked)paintFlags=paintFlags or Paint.STRIKE_THRU_TEXT_FLAG;setOnCheckedChangeListener{_,v->activity.database.setShopping(i.id,v);showShopping()};setOnLongClickListener{AlertDialog.Builder(activity).setMessage("Usunąć produkt „${i.title}”? ").setPositiveButton("Usuń"){_,_->activity.database.deleteShopping(i.id);showShopping()}.setNegativeButton("Anuluj",null).show();true}})};body.addView(action("Wyczyść odhaczone"){activity.database.clearCheckedShopping();showShopping()})}
    private fun shoppingDialog(){val input=EditText(activity).apply{hint="Produkt"};AlertDialog.Builder(activity).setTitle("Nowy produkt").setView(input).setPositiveButton("Dodaj"){_,_->if(input.text.trim().isNotEmpty()){activity.database.addShopping(input.text.toString());showShopping()}}.setNegativeButton("Anuluj",null).show()}
    fun showCalendar(){val body=base("Kalendarz");body.addView(text("Wybierz dzień, aby zobaczyć jego wpisy i postęp.",15f,sage));body.addView(action("Wybierz datę: $label"){DatePickerDialog(activity,{_,y,m,d->activity.selectedDate.set(y,m,d);showTasks()},activity.selectedDate.get(1),activity.selectedDate.get(2),activity.selectedDate.get(5)).show()}.apply{background=shape(Color.WHITE)})}
    fun showPhotos(){val body=base("Zdjęcie dnia");val photo=activity.database.record(day).photoUri;body.addView(text("Jedno prywatne zdjęcie przypisane do dnia. Kadrowanie gestem wymaga osobnego, przetestowanego komponentu i nie zostało pozorowane.",15f,sage));if(photo!=null)body.addView(ImageView(activity).apply{contentDescription="Zdjęcie dnia";scaleType=ImageView.ScaleType.CENTER_CROP;runCatching{setImageURI(android.net.Uri.parse(photo))};background=shape(Color.WHITE)},LinearLayout.LayoutParams(-1,dp(260)).apply{topMargin=dp(12)});body.addView(action(if(photo==null)"Dodaj zdjęcie" else "Zmień zdjęcie"){activity.pickPhoto()}.apply{background=shape(Color.WHITE)})}
    fun showStats(){val body=base("Statystyki");val h=activity.database.habits();body.addView(card("Dzisiaj",progress()){showTasks()});body.addView(text("Statystyki historii będą liczone z zapisanych wykonań, podzadań i aktywnych dni. Nie pokazujemy fikcyjnych danych.",15f,sage).apply{setPadding(0,dp(12),0,0)})}
    fun showMore(){val body=base("Więcej");listOf("Ogród" to "garden","Kuchnia" to "kitchen","Podróże" to "travel","Ustawienia" to "settings").forEach{(n,r)->body.addView(card(n,"Przestrzeń gotowa do rozbudowy."){activity.open(r)},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)})}}
    fun showSettings(){val body=base("Ustawienia");body.addView(action("Wybierz tło"){chooseBackground()}.apply{background=shape(Color.WHITE)});body.addView(text("Dane lokalne pozostają tylko na tym urządzeniu. Migracja poprzednich wpisów jest zachowana.",15f,sage).apply{setPadding(0,dp(14),0,0)})}
    fun showPlaceholder(name:String){val body=base(name.replaceFirstChar{it.uppercase()});body.addView(text("To miejsce jest przygotowane jako pusty moduł — nie dodaliśmy przykładowych danych.",15f,sage))}
    private fun noteDialog(){val input=EditText(activity).apply{setText(activity.database.record(day).note);minLines=5};AlertDialog.Builder(activity).setTitle("Notatka dnia").setView(input).setPositiveButton("Zapisz"){_,_->activity.database.saveNote(day,input.text.toString())}.setNegativeButton("Anuluj",null).show()}
    private fun chooseBackground(){AlertDialog.Builder(activity).setTitle("Wybierz tło").setSingleChoiceItems(arrayOf("Jezioro","Las","Góry","Trawy","Łąka"),prefs.getInt("background",0)){d,w->prefs.edit().putInt("background",w).apply();d.dismiss();showSettings()}.show()}
}
